### ISSUE TITLE
HCL locals

### ISSUE THREAD

**Issue by skorfmann** [iann0036/hcl2cdktf#1]
I'm wondering how to handle `locals`, e.g.

```hcl
locals {
  s3_origin_id = "myS3Origin"
}
```

Rather converting them 1:1, would it make sense to convert them to variables in typescript?

```ts
  const s3_origin_id = "myS3Origin"
```

**Comment by jsteinich** [comment]
Most places that I've used locals involve expressions which I don't believe are fully representable in typescript currently.

**Comment by skorfmann** [comment]
> Most places that I've used locals involve expressions which I don't believe are fully representable in typescript currently.

Good point 👍  `locals` could use an [escape hatch](https://cdk.tf/escape-hatch) for now.

**Comment by iann0036** [comment]
Cheers!

Added as an escape hatch. Any others in a similar position to `locals` that would have the same treatment?

**Comment by iann0036** [comment]
Actually, how would you reference the value from elsewhere? (if at all)

**Comment by skorfmann** [comment]
> Actually, how would you reference the value from elsewhere? (if at all)

`const s3_origin_id = "${local.s3_origin_id}"` something like this would work, I think.

**Comment by iann0036** [comment]
Latest version should work as described, tested with the example at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution

**Comment by skorfmann** [comment]
Cool - just a little issue: the override is camel cased, where the reference is snake cased. Since overrides aren't post processed, this leads to an error.

**Comment by iann0036** [comment]
Good pick up!

New format is like:

```
this.addOverride('locals', {
    s3_origin_id: "myS3Origin"
});

new CloudfrontDistribution(this, 's3_distribution', {
    
    ...

    ],
    origin: [{
        domainName: "${aws_s3_bucket.b.bucket_regional_domain_name}",
        originId: "${local.s3_origin_id}",
    
    ...
```

Let me know if it is more Terraform-y to have this as always camel cased instead of always snake cased.
