### ISSUE TITLE
Don't generate variable assignments for unused references 

### ISSUE THREAD

**Issue by skorfmann** [iann0036/hcl2cdktf#6]
If a resource is not reference, the variable assignment should be omitted, since it will be marked as lint error.

That's how it's generated:

```ts
  const b = new S3Bucket(this, 'b', {
    acl: "private",
    bucket: "mybucket",
    tags: {
        Name: "My bucket"
    }
});
```

That's how it should be:

```ts
  new S3Bucket(this, 'b', {
    acl: "private",
    bucket: "mybucket",
    tags: {
        Name: "My bucket"
    }
});
```

**Comment by iann0036** [comment]
Currently using console.debug at the end of the template to make TypeScript not complain (yes, this is dirty!).

Will look into post-processing to remove this.

**Comment by iann0036** [comment]
Fully fixed with referenced commit.
